"""Compatibility generator for IEEE figures.

The previous script created formula-driven curves. Publication figures are now
generated by the canonical backend package from live model/test computations.
"""

from backend.generate_publication_package import build_package


if __name__ == "__main__":
    package = build_package()
    print(f"Generated {len(package['figures'])} empirical publication figures.")
