import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
import joblib
import json
from src.project_paths import METRICS_PATH, MODEL_DIR, MODEL_PATH, RESULTS_DIR, TEST_PATH, TRAIN_PATH

RESULTS_JSON = METRICS_PATH


def load_data():
    train_df = pd.read_csv(TRAIN_PATH)
    test_df = pd.read_csv(TEST_PATH)
    label_col = "label"
    X_train = train_df.drop(columns=[label_col])
    y_train = train_df[label_col]
    X_test = test_df.drop(columns=[label_col])
    y_test = test_df[label_col]
    return X_train, X_test, y_train, y_test


def train_model():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    MODEL_DIR.mkdir(parents=True, exist_ok=True)

    X_train, X_test, y_train, y_test = load_data()
    classes = sorted(y_train.unique())

    mlp = MLPClassifier(
        hidden_layer_sizes=(128, 64),
        activation="relu",
        solver="adam",
        max_iter=25,
        random_state=42,
    )
    mlp.fit(X_train, y_train)

    y_pred = mlp.predict(X_test)

    report = classification_report(y_test, y_pred, output_dict=True, zero_division=0)
    print("Classification report:")
    print(classification_report(y_test, y_pred, zero_division=0))

    # proposed metrics
    macro_avg = report.get("macro avg", {})
    proposed_precision = macro_avg.get("precision", 0.0)
    proposed_recall = macro_avg.get("recall", 0.0)
    proposed_f1 = macro_avg.get("f1-score", 0.0)
    proposed_accuracy = report.get("accuracy", 0.0)

    metrics_summary = {
        "classes": classes,
        "classification_report": report,
        "proposed": {
            "accuracy": proposed_accuracy,
            "precision_macro": proposed_precision,
            "recall_macro": proposed_recall,
            "f1_macro": proposed_f1,
        },
        "paper_summary_note": "No paper-baseline values are generated by train_model.py; live baseline metrics are computed by backend.nids_engine.",
    }

    with open(RESULTS_JSON, "w", encoding="utf-8") as f:
        json.dump(metrics_summary, f, indent=4)

    joblib.dump(mlp, MODEL_PATH)
    print(f"Training completed. Metrics saved to {RESULTS_JSON} and model to {MODEL_PATH}.")


if __name__ == "__main__":
    train_model()
